#!/usr/bin/env python3
#pyright: reportUnboundVariable=false

import pandas as pd
import matplotlib.pyplot as plt
import multiprocessing
import os
import upsetplot
import argparse


parser = argparse.ArgumentParser()

parser.add_argument('--venn', 
                    help = '<Required> Input venn .txt table, as generated by HOMER MergePeaks', 
                    required = True)

parser.add_argument('--prefix', 
                    help = '<Required> File prefix to be used in the output name', 
                    required = True)

args = parser.parse_args()


cpu_count = multiprocessing.cpu_count()

input_path = os.path.abspath(args.venn)
input_filename = input_path.split('/')[-1]
input_folder = input_path.rstrip(input_filename)

intersection_df = pd.read_csv(input_path, delimiter = '\t')

set_label_df = intersection_df['Name']
set_label_df = set_label_df.apply(lambda x : x.split('|'))
set_label_list = set_label_df.values.tolist()

set_count_list = intersection_df['Total'].values.tolist()


intersection_series = upsetplot.from_memberships(set_label_list, data = set_count_list)
upsetplot.plot(intersection_series, sort_by = '-degree', show_counts = True, show_percentages = False)

plt.title(args.prefix)
plt.savefig('{}/{}_peakset_intersections.png'.format(input_folder, args.prefix), dpi = 300)
plt.clf()